version: "3"
services:
  nginx:
    image: "upd_nginx"
    build:
      context: ../
      dockerfile: docker/performance_nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped
    container_name: upd_nginx
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  web:
    image: "upd_web"
    container_name: upd_web
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/performance_web/Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
    ports:
      - "9000"
  mongodb:
    image: mongo:4.4
    container_name: upd_mongo
    restart: unless-stopped
    volumes:
      - /datadrive/db/data:/data
