version: "3"
services:
  nginx:
    image: "upd_nginx"
    build:
      context: ../
      dockerfile: docker/performance_nginx/Dockerfile
    ports:
      - "81:81"
      - "443:443"
    depends_on:
      - web
    restart: unless-stopped
    container_name: upd_nginx
  web:
    image: "upd_web"
    container_name: upd_web
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/performance_web/Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTP_PROXY}
    ports:
      - "9000"
  mongodb:
    image: mongo:4.4
    container_name: upd_mongo
    restart: unless-stopped
    volumes:
      - ~/db/data:/data
