name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.3
    with:
      parallel-commands: |
        npx nx workspace-lint
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel
        npx nx affected --target=build --parallel --maxParallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.3
    with:
      number-of-agents: 3
